### ISSUE TITLE
License matching query does not exist

### ISSUE THREAD

**Issue by raratiru** [raratiru/django-quenv#2]
```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/python.py", line 147, in Deserializer
    m2m_data[field.name].append(m2m_convert(pk))
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/python.py", line 137, in m2m_convert
    return model._default_manager.db_manager(db).get_by_natural_key(*value).pk
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/quenv/managers.py", line 21, in get_by_natural_key
    return self.get(license_name=license_name)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
quenv.models.DoesNotExist: License matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/python.py", line 149, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), pk)
django.core.serializers.base.DeserializationError: License matching query does not exist.: (quenv.info:pk=None) field_value was '['Version 2.0']'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/quenv/management/commands/quenv.py", line 23, in handle
    obj.dump()
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/quenv/licenses.py", line 337, in dump
    format=json
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
    for obj in objects:
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/json.py", line 88, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/user/.virtualenvs/app/lib/python3.5/site-packages/django/core/serializers/python.py", line 149, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), pk)
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/user/02/era/00/fixtures/2019-05-06.json': License matching query does not exist.: (quenv.info:pk=None) field_value was '['Version 2.0']'
```

**Comment by raratiru** [comment]
`rcssmin` is one of the packages that cause the issue:

```
 'Classifier: License :: OSI Approved',
 'Classifier: License :: OSI Approved :: Apache License, Version 2.0',
```

```
>>> g = Package('rcssmin')
>>> g.info().classifier_licenses
['OSI Approved', 'Apache License, Version 2.0']
```
In fixtures:
```
"licenses_keys": [                                                  
     [                                                               
         "OSI Approved"                                              
    ],                                                              
    [                                                               
         "Apache License"                                            
    ],                                                              
    [                                                               
         "Version 2.0"                                               
    ]                                                               
],                                           
```
Lines that cause the issue:
https://github.com/raratiru/django-quenv/blob/20eb25efb80fbe4419142d5d6bb3a2c507a7cfe2/quenv/licenses.py#L91-L108

https://github.com/raratiru/django-quenv/blob/20eb25efb80fbe4419142d5d6bb3a2c507a7cfe2/quenv/licenses.py#L190-L203
